-- CoverWise canonical production schema.
-- Apply this migration in the Supabase SQL editor before enabling the
-- Supabase repository/object-store backends in Cloud Run.

create extension if not exists vector;

create table if not exists public.documents (
  id uuid primary key,
  owner_id text not null,
  source_hash text not null,
  payload jsonb not null,
  status text not null default 'received',
  object_reference text not null,
  processing_attempts integer not null default 0,
  processing_started_at timestamptz,
  processing_lease_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists documents_owner_created_idx
  on public.documents (owner_id, created_at desc);
create unique index if not exists documents_owner_source_hash_unique
  on public.documents (owner_id, source_hash);
create index if not exists documents_recovery_idx
  on public.documents (status, processing_lease_expires_at);

create or replace function public.claim_document_processing(
  p_document_id uuid,
  p_owner_id text,
  p_lease_seconds integer default 900
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.documents
  set
    status = 'processing',
    processing_attempts = processing_attempts + 1,
    processing_started_at = now(),
    processing_lease_expires_at = now() + make_interval(secs => p_lease_seconds),
    updated_at = now(),
    payload = payload || jsonb_build_object(
      'status', 'processing',
      'processing_attempts', processing_attempts + 1,
      'processing_started_at', now(),
      'processing_lease_expires_at', now() + make_interval(secs => p_lease_seconds)
    )
  where id = p_document_id
    and owner_id = p_owner_id
    and (
      status = 'received'
      or (status = 'processing' and processing_lease_expires_at <= now())
    );
  return found;
end;
$$;

revoke all on function public.claim_document_processing(uuid, text, integer)
  from public, anon, authenticated;
grant execute on function public.claim_document_processing(uuid, text, integer)
  to service_role;

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  owner_id text not null,
  chunk_index integer not null,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(1536),
  created_at timestamptz not null default now(),
  unique (document_id, chunk_index)
);

create index if not exists document_chunks_owner_idx on public.document_chunks (owner_id);
create index if not exists document_chunks_embedding_hnsw_idx
  on public.document_chunks using hnsw (embedding vector_cosine_ops)
  where embedding is not null;

alter table public.documents enable row level security;
alter table public.document_chunks enable row level security;

create or replace function public.match_document_chunks(
  query_embedding vector(1536),
  match_owner_id text,
  match_count integer default 8,
  match_threshold double precision default 0.20
)
returns table (id bigint, document_id uuid, content text, metadata jsonb, similarity double precision)
language sql stable
as $$
  select c.id, c.document_id, c.content, c.metadata,
         1 - (c.embedding <=> query_embedding) as similarity
  from public.document_chunks c
  where c.owner_id = match_owner_id
    and c.embedding is not null
    and 1 - (c.embedding <=> query_embedding) >= match_threshold
  order by c.embedding <=> query_embedding
  limit least(match_count, 50);
$$;

insert into storage.buckets (id, name, public)
values ('coverwise-documents', 'coverwise-documents', false)
on conflict (id) do nothing;

comment on table public.documents is 'CoverWise owner-scoped policy document metadata';
comment on table public.document_chunks is 'CoverWise policy chunks and pgvector embeddings';
