"""Evidence extraction pipeline (Trust Phase 1 Phase C).

The orchestrator that turns an uploaded document into cited fields
in the evidence substrate. Calls the 6 deterministic extractors and
1 LLM extractor defined inline, persists results via the
EvidenceSubstrateService, and writes cost records to
evidence_extraction_costs for every field.

The pipeline is the only path that produces extracted_fields. UI
surfaces, Q&A, claim verification, and renewal diff all read from
the substrate; they do not call extractors directly. Per motto v3
§0.1 (no parallel paths), there is exactly one pipeline.

Append-only contract: every run produces rows with a fresh
parser_version. Re-running the pipeline on a document does not
delete prior rows. The UI shows the latest row per (document,
field) by created_at; older rows remain for audit.

LLM honesty check: every LLM-extracted field is verified against
the source text before the citation is written. If the structured
output contains a clause that the page text does not contain, the
candidate is rejected and no unverified value enters the substrate.
This is the substrate's defense against the most common LLM failure
mode: citing text that isn't there.
"""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional, Protocol
from uuid import UUID

from src.models.evidence import (
    ExtractedValue,
    ExtractionCostRecord,
    ParserKind,
    ValueType,
)
from src.security.prompt_injection import fence_untrusted_content
from src.models.extraction import RoomRentCapExtraction
from src.services.evidence_substrate_service import (
    EvidenceSubstrateService,
    EvidenceSubstrateUnavailable,
)

log = logging.getLogger(__name__)


# --- 1. Extractor protocol ---

@dataclass
class ExtractorResult:
    """The shape every extractor returns. The pipeline turns this
    into substrate rows. page_artifact_id is required; the span is
    optional for v1 of the layout parser (which only does
    page-level citation, not span-level)."""

    field_name: str
    value: ExtractedValue
    value_type: ValueType
    confidence: float
    page_artifact_id: UUID
    source_span_id: Optional[UUID] = None
    evidence_strength: float = 1.0
    cite_string: str = ""  # generated by the pipeline if empty


class Extractor(Protocol):
    """An extractor takes a document's pages and returns one or
    more ExtractorResult. Deterministic extractors return 0 or 1
    result (the field is either present or not). LLM extractors
    may return 0 or 1."""

    field_name: str
    parser_kind: ParserKind

    async def extract(
        self, document_id: UUID, page_texts: dict[int, str]
    ) -> Optional[ExtractorResult]: ...


# --- 2. Deterministic extractors ---
# Each is a small, focused regex/lookup. The pattern is the same:
# iterate pages in order, return the first match with the
# strongest evidence.

_POLICY_NUMBER_RE = re.compile(
    r"(?i)policy\s*(?:no|number|#)\s*[:\-]?\s*([A-Z0-9][A-Z0-9\-\/]{4,})"
)
_POLICY_HOLDER_RE = re.compile(
    r"(?im)^\s*(?:policy\s*holder|insured\s*name|name\s*of\s*the\s*insured)"
    r"\s*[:\-]\s*(.+?)\s*$"
)
_SUM_INSURED_RE = re.compile(
    r"(?i)sum\s*insured\s*[:\-]?\s*(?:rs\.?|inr|₹)?\s*([0-9][0-9,]*\.?[0-9]*)"
)
_DATE_ISO_RE = re.compile(r"\b(\d{4}-\d{2}-\d{2})\b")
_DATE_DMY_RE = re.compile(r"\b(\d{1,2}[-\/]\d{1,2}[-\/]\d{2,4})\b")
_PREMIUM_RE = re.compile(
    r"(?i)premium\s*(?:amount)?\s*[:\-]?\s*(?:rs\.?|inr|₹)?\s*([0-9][0-9,]*\.?[0-9]*)"
)
_INSURER_NAMES = (
    "hdfc ergo", "icici lombard", "bajaj allianz", "tata aig",
    "new india assurance", "oriental insurance", "national insurance",
    "united india", "reliance general", "iffco tokio", "sbi general",
    "star health", "manipalcigna", "niva bupa", "aditya birla health",
    "care health", "max bupa", "digit", "acko", "go digit", "zuno",
    "future generali", "cholamandalam", "edelweiss", "kotak general",
    "liberty general", "raheja qbe", "universal sompo", "bharti axa",
    "royal sundaram", "shriram general", "magma hdi",
)


def _first_match(re_obj: re.Pattern, text: str) -> Optional[re.Match]:
    return re_obj.search(text)


def _parse_currency_to_paise(raw: str) -> int:
    """Convert '5,00,000' or '5,00,000.50' to integer paise. INR
    convention is lakh/crore grouping, but the regex matches
    standard Western commas too. Returns 0 on parse failure."""
    cleaned = raw.replace(",", "").strip()
    try:
        rupees = float(cleaned)
        return int(round(rupees * 100))
    except ValueError:
        return 0


def _format_inr(paise: int) -> str:
    """Render paise as Indian-grouped rupees: 50000000 -> ₹5,00,000."""
    rupees = paise // 100
    s = str(rupees)
    if len(s) <= 3:
        return f"₹{s}"
    # Last 3 digits, then groups of 2 from the right
    last_three = s[-3:]
    rest = s[:-3]
    groups = []
    while len(rest) > 2:
        groups.append(rest[-2:])
        rest = rest[:-2]
    if rest:
        groups.append(rest)
    return "₹" + ",".join(reversed(groups)) + "," + last_three


class PolicyNumberExtractor:
    field_name = "policy_number"
    parser_kind = ParserKind.DETERMINISTIC_REGEX

    async def extract(
        self, document_id: UUID, page_texts: dict[int, str]
    ) -> Optional[ExtractorResult]:
        # Prefer page 1 (most policies print the number on page 1)
        for page_num in sorted(page_texts):
            m = _first_match(_POLICY_NUMBER_RE, page_texts[page_num])
            if m:
                raw = m.group(1)
                return ExtractorResult(
                    field_name=self.field_name,
                    value=ExtractedValue(
                        raw=raw, normalized=raw, display=raw,
                    ),
                    value_type=ValueType.STRING,
                    confidence=0.9,
                    page_artifact_id=UUID(int=0),  # filled by pipeline
                    cite_string=f"page {page_num}",
                )
        return None


class PolicyHolderExtractor:
    field_name = "policy_holder_name"
    parser_kind = ParserKind.DETERMINISTIC_REGEX

    async def extract(
        self, document_id: UUID, page_texts: dict[int, str]
    ) -> Optional[ExtractorResult]:
        for page_num in sorted(page_texts):
            m = _first_match(_POLICY_HOLDER_RE, page_texts[page_num])
            if m:
                raw = m.group(1).strip()
                return ExtractorResult(
                    field_name=self.field_name,
                    value=ExtractedValue(
                        raw=raw, normalized=raw, display=raw.title(),
                    ),
                    value_type=ValueType.STRING,
                    confidence=0.85,
                    page_artifact_id=UUID(int=0),
                    cite_string=f"page {page_num}",
                )
        return None


class SumInsuredExtractor:
    field_name = "sum_insured"
    parser_kind = ParserKind.DETERMINISTIC_REGEX

    async def extract(
        self, document_id: UUID, page_texts: dict[int, str]
    ) -> Optional[ExtractorResult]:
        for page_num in sorted(page_texts):
            m = _first_match(_SUM_INSURED_RE, page_texts[page_num])
            if m:
                raw = m.group(1)
                paise = _parse_currency_to_paise(raw)
                if paise <= 0:
                    continue
                return ExtractorResult(
                    field_name=self.field_name,
                    value=ExtractedValue(
                        raw=raw, normalized=paise, display=_format_inr(paise),
                    ),
                    value_type=ValueType.CURRENCY,
                    confidence=0.95,
                    page_artifact_id=UUID(int=0),
                    cite_string=f"page {page_num}",
                )
        return None


class PolicyStartDateExtractor:
    field_name = "policy_start_date"
    parser_kind = ParserKind.DETERMINISTIC_REGEX

    async def extract(
        self, document_id: UUID, page_texts: dict[int, str]
    ) -> Optional[ExtractorResult]:
        for page_num in sorted(page_texts):
            text = page_texts[page_num]
            m = _first_match(_DATE_ISO_RE, text) or _first_match(
                _DATE_DMY_RE, text
            )
            if m:
                raw = m.group(1)
                # Try to normalize; fall back to raw
                normalized = raw
                try:
                    if "-" in raw and len(raw) == 10:
                        normalized = raw
                    else:
                        # DMY -> assume DD/MM/YYYY for Indian policies
                        parts = re.split(r"[-\/]", raw)
                        if len(parts) == 3:
                            d, mo, y = parts
                            if len(y) == 2:
                                y = "20" + y
                            normalized = f"{y}-{int(mo):02d}-{int(d):02d}"
                except (ValueError, IndexError):
                    normalized = raw
                return ExtractorResult(
                    field_name=self.field_name,
                    value=ExtractedValue(
                        raw=raw, normalized=normalized, display=normalized,
                    ),
                    value_type=ValueType.DATE,
                    confidence=0.8,
                    page_artifact_id=UUID(int=0),
                    cite_string=f"page {page_num}",
                )
        return None


class PremiumAmountExtractor:
    field_name = "premium_amount"
    parser_kind = ParserKind.DETERMINISTIC_REGEX

    async def extract(
        self, document_id: UUID, page_texts: dict[int, str]
    ) -> Optional[ExtractorResult]:
        for page_num in sorted(page_texts):
            m = _first_match(_PREMIUM_RE, page_texts[page_num])
            if m:
                raw = m.group(1)
                paise = _parse_currency_to_paise(raw)
                if paise <= 0:
                    continue
                return ExtractorResult(
                    field_name=self.field_name,
                    value=ExtractedValue(
                        raw=raw, normalized=paise, display=_format_inr(paise),
                    ),
                    value_type=ValueType.CURRENCY,
                    confidence=0.9,
                    page_artifact_id=UUID(int=0),
                    cite_string=f"page {page_num}",
                )
        return None


class InsurerNameExtractor:
    field_name = "insurer_name"
    parser_kind = ParserKind.DETERMINISTIC_LOOKUP

    async def extract(
        self, document_id: UUID, page_texts: dict[int, str]
    ) -> Optional[ExtractorResult]:
        for page_num in sorted(page_texts):
            text = page_texts[page_num].lower()
            for name in _INSURER_NAMES:
                if name in text:
                    display = name.title()
                    return ExtractorResult(
                        field_name=self.field_name,
                        value=ExtractedValue(
                            raw=name, normalized=name, display=display,
                        ),
                        value_type=ValueType.STRING,
                        confidence=1.0,
                        page_artifact_id=UUID(int=0),
                        cite_string=f"page {page_num}",
                    )
        return None


# --- 3. LLM extractor (room_rent_cap) ---

_ROOM_RENT_CAP_PROMPT = """You are extracting the room rent cap clause from an
Indian health insurance policy document.

Read the text below. If a room rent cap (or room rent limit, or
"eligible room rent") is mentioned, return:
  {"present": true, "clause": "<the exact clause text>", "display": "<short human summary, e.g. '1% of sum insured, max ₹5,000/day'>"}

If no room rent cap is present, return:
  {"present": false}

Return only JSON. No commentary.

TEXT:
"""


class RoomRentCapExtractor:
    field_name = "room_rent_cap"
    parser_kind = ParserKind.LLM_EXTRACT

    def __init__(self, llm_client, model: str = "gpt-4o-mini"):
        self._llm = llm_client
        self._model = model

    async def extract(
        self, document_id: UUID, page_texts: dict[int, str]
    ) -> Optional[ExtractorResult]:
        # Concatenate all pages (cap to ~30k chars to keep the
        # prompt under the model's context window with margin).
        full_text = "\n\n".join(
            page_texts[p] for p in sorted(page_texts)
        )[:30000]
        try:
            payload = await self._llm.generate_structured(
                messages=[
                    {"role": "system", "content": "You extract structured data from insurance policy text. Respond only with JSON."},
                    {"role": "user", "content": _ROOM_RENT_CAP_PROMPT + fence_untrusted_content("evidence_document", full_text, max_chars=30000)},
                ],
                response_model=RoomRentCapExtraction,
                temperature=0.0,
            )
        except Exception as error:
            log.warning("room_rent_cap LLM call failed: %s", error)
            return None
        if not payload.present:
            return None
        clause = payload.clause.strip()
        display = payload.display.strip()
        if not clause or not display:
            return None
        # Find the page that contains the clause (the honesty check).
        cite_page = None
        for page_num in sorted(page_texts):
            if clause[:80] in page_texts[page_num]:
                cite_page = page_num
                break
        if cite_page is None:
            # LLM cited a clause that isn't on any page. Reject.
            log.warning(
                "room_rent_cap LLM cited a clause not found in any page; rejecting"
            )
            return None
        return ExtractorResult(
            field_name=self.field_name,
            value=ExtractedValue(
                raw=clause, normalized=display, display=display,
            ),
            value_type=ValueType.CLAUSE_TEXT,
            confidence=0.85,
            page_artifact_id=UUID(int=0),
            cite_string=f"page {cite_page}",
        )


# --- 4. Pipeline orchestrator ---

@dataclass
class PipelineResult:
    document_id: UUID
    fields_extracted: int
    fields_cited: int
    fields_rejected: int  # evidence_strength = 0.0
    total_cost_usd: float
    parser_version: str
    duration_seconds: float


class EvidencePipeline:
    """The orchestrator. One instance per document. Runs all
    extractors, persists results to the substrate, and emits
    cost records."""

    def __init__(
        self,
        substrate: EvidenceSubstrateService,
        llm_client=None,
    ):
        self._substrate = substrate
        self._llm = llm_client
        # Parser version is timestamp-based so re-runs produce new
        # rows (the substrate is append-only; v1 of the UI shows
        # the latest by created_at).
        self._parser_version = (
            f"evidence-pipeline-v1-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"
        )
        self._deterministic_extractors: list[Extractor] = [
            PolicyNumberExtractor(),
            PolicyHolderExtractor(),
            SumInsuredExtractor(),
            PolicyStartDateExtractor(),
            PremiumAmountExtractor(),
            InsurerNameExtractor(),
        ]
        self._llm_extractors: list[Extractor] = []
        if llm_client is not None:
            self._llm_extractors.append(
                RoomRentCapExtractor(llm_client=llm_client)
            )

    async def run_for_document(
        self,
        document_id: UUID,
        page_texts: dict[int, str],
    ) -> PipelineResult:
        """Run all extractors against the document's pages and
        write results to the substrate.

        page_texts is a dict {page_number: text}. The pipeline
        does not render pages or run OCR; that is the caller's
        responsibility (or a future pipeline stage)."""
        start = datetime.now(timezone.utc)
        fields_extracted = 0
        fields_cited = 0
        fields_rejected = 0
        total_cost_usd = 0.0

        # Build the page_artifact_id lookup. The substrate has
        # the rows from the previous pipeline stage; we look them
        # up by (document_id, page_number).
        page_artifact_ids: dict[int, UUID] = {}
        try:
            pages = await self._substrate.get_page_artifacts_for_document(
                document_id
            )
            for page in pages:
                page_artifact_ids[page.page_number] = UUID(page.id)
        except EvidenceSubstrateUnavailable as error:
            log.error("substrate unavailable: %s", error)
            raise

        extractors = self._deterministic_extractors + self._llm_extractors
        for extractor in extractors:
            try:
                result = await extractor.extract(document_id, page_texts)
            except Exception as error:
                log.warning(
                    "extractor %s failed: %s", extractor.field_name, error
                )
                continue
            if result is None:
                # Field not present in this document; record a
                # zero-cost row so the operator dashboard knows
                # the pipeline tried.
                await self._substrate.record_extraction_cost(
                    ExtractionCostRecord(
                        document_id=str(document_id),
                        extracted_field_id=None,
                        parser_kind=extractor.parser_kind,
                        model=None,
                        cost_usd=0.0,
                    )
                )
                continue
            # Resolve the page_artifact_id from the page number
            page_num = self._parse_page_number_from_cite(result.cite_string)
            if page_num is None or page_num not in page_artifact_ids:
                # No page artifact for the cited page; reject the field.
                log.warning(
                    "extractor %s cited page %s but no page_artifact exists; rejecting",
                    extractor.field_name, page_num,
                )
                fields_rejected += 1
                continue
            result.page_artifact_id = page_artifact_ids[page_num]

            # Persist the extracted_field
            field_id = await self._substrate.append_extracted_field(
                document_id=document_id,
                field_name=result.field_name,
                value=result.value,
                value_type=result.value_type,
                confidence=result.confidence,
                parser_version=self._parser_version,
                parser_kind=extractor.parser_kind,
            )
            fields_extracted += 1

            # Persist the field_evidence (citation link)
            if result.evidence_strength > 0.0 and result.cite_string:
                await self._substrate.link_field_evidence(
                    extracted_field_id=field_id,
                    page_artifact_id=result.page_artifact_id,
                    source_span_id=result.source_span_id,
                    cite_string=result.cite_string,
                    evidence_strength=result.evidence_strength,
                )
                fields_cited += 1
            else:
                fields_rejected += 1

            # Persist the cost record. LLM extractors carry cost;
            # deterministic ones get cost_usd=0.
            if extractor.parser_kind == ParserKind.LLM_EXTRACT:
                # The LLM call already happened inside the
                # extractor. We don't have token counts in v1;
                # record a placeholder so the dashboard row exists.
                cost = 0.0  # populated by the LLM call wrapper in v2
            else:
                cost = 0.0
            await self._substrate.record_extraction_cost(
                ExtractionCostRecord(
                    document_id=str(document_id),
                    extracted_field_id=str(field_id),
                    parser_kind=extractor.parser_kind,
                    model=(
                        getattr(extractor, "_model", None)
                        if extractor.parser_kind == ParserKind.LLM_EXTRACT
                        else None
                    ),
                    cost_usd=cost,
                )
            )
            total_cost_usd += cost

        end = datetime.now(timezone.utc)
        return PipelineResult(
            document_id=document_id,
            fields_extracted=fields_extracted,
            fields_cited=fields_cited,
            fields_rejected=fields_rejected,
            total_cost_usd=total_cost_usd,
            parser_version=self._parser_version,
            duration_seconds=(end - start).total_seconds(),
        )

    @staticmethod
    def _parse_page_number_from_cite(cite_string: str) -> Optional[int]:
        """Extract the page number from a cite string like 'page 4'
        or 'page 4, paragraph 3'. Returns None if no page number
        is present."""
        m = re.search(r"page\s+(\d+)", cite_string, re.IGNORECASE)
        if m:
            try:
                return int(m.group(1))
            except ValueError:
                return None
        return None
