-- CoverWise analytics_events in Supabase (Phase R1.2)
-- Date: 2026-07-18
--
-- Replaces the current SQLite analytics_events table (insurance_app.db).
-- One-time migration is via tools/migrate/sqlite_analytics_to_supabase.py
-- with --dry-run first, then live.
--
-- Schema mirrors the current SQLite columns plus 3 new columns for RevOps:
--   - install_id uuid  : ties events to a specific install (re-install detectable)
--   - session_id uuid  : ties events to a specific app session
--   - is_reinstall boolean
--
-- Idempotency: the (received_at, event_name, user_uid) UNIQUE constraint allows
-- the migration script to use ON CONFLICT DO NOTHING for safe replay.
--
-- Apply via Supabase SQL editor or:
--   psql "$SUPABASE_DB_URL" -f supabase/migrations/2026_07_18_analytics_supabase.sql

create extension if not exists pgcrypto;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  timestamp timestamptz not null,
  user_uid text not null,
  properties jsonb,
  received_at timestamptz not null default now(),
  install_id uuid,
  session_id uuid,
  is_reinstall boolean not null default false,
  unique (received_at, event_name, user_uid)
);

-- Indexes (matched from src/api/analytics.py usage patterns)
create index if not exists idx_analytics_event_name
  on public.analytics_events (event_name);

create index if not exists idx_analytics_user_uid
  on public.analytics_events (user_uid);

create index if not exists idx_analytics_error_window
  on public.analytics_events (event_name, received_at);

-- Covering index for the /analytics/summary endpoint (time filter + GROUP BY + COUNT DISTINCT)
create index if not exists idx_analytics_summary
  on public.analytics_events (received_at, event_name, user_uid);

-- New: install_id index for cohort + re-install detection
create index if not exists idx_analytics_install_id
  on public.analytics_events (install_id)
  where install_id is not null;

-- New: session_id index for session-scoped queries
create index if not exists idx_analytics_session_id
  on public.analytics_events (session_id)
  where session_id is not null;

alter table public.analytics_events enable row level security;

-- Service-role only. Clients never write directly to analytics_events; they
-- always go through /analytics/events which runs as service_role.
revoke all on table public.analytics_events from public, anon, authenticated;
grant select, insert, update, delete on table public.analytics_events to service_role;

comment on table public.analytics_events is
  'Canonical analytics events. Source of truth for the operator dashboard. Service-role only. No PII per docs/review/coverwise_analytics_event_spec.md.';


-- ============================================================================
-- Dashboard views (Phase R4 uses these; created here for forward consistency)
-- ============================================================================

-- Daily active users
create or replace view public.v_daily_active_users as
select
  date_trunc('day', timestamp) as day,
  count(distinct user_uid) as dau
from public.analytics_events
where event_name = 'app_session_started'
  and timestamp > now() - interval '90 days'
group by day
order by day desc;

-- Conversion funnel (install -> extract -> ask -> answer -> paywall -> paying)
create or replace view public.v_conversion_funnel as
select
  date_trunc('day', timestamp) as day,
  count(distinct case when event_name = 'app_session_started' then user_uid end) as installs,
  count(distinct case when event_name = 'document_processing_succeeded' then user_uid end) as extracted,
  count(distinct case when event_name = 'question_submitted' then user_uid end) as asked,
  count(distinct case when event_name = 'answer_rendered' then user_uid end) as activated,
  count(distinct case when event_name = 'paywall_viewed' then user_uid end) as paywall,
  count(distinct case when event_name = 'subscription_started' then user_uid end) as paying
from public.analytics_events
where timestamp > now() - interval '90 days'
group by day
order by day desc;

-- Cohort retention (D1, D7, D30)
create or replace view public.v_cohort_retention as
with cohorts as (
  select
    user_uid,
    date_trunc('day', min(timestamp)) as cohort_day
  from public.analytics_events
  where event_name = 'app_session_started'
  group by user_uid
)
select
  c.cohort_day,
  count(distinct c.user_uid) as cohort_size,
  count(distinct case
    when e.timestamp >= c.cohort_day + interval '1 day'
     and e.timestamp <  c.cohort_day + interval '2 days'
    then e.user_uid
  end) as d1_active,
  count(distinct case
    when e.timestamp >= c.cohort_day + interval '7 days'
     and e.timestamp <  c.cohort_day + interval '8 days'
    then e.user_uid
  end) as d7_active,
  count(distinct case
    when e.timestamp >= c.cohort_day + interval '30 days'
     and e.timestamp <  c.cohort_day + interval '31 days'
    then e.user_uid
  end) as d30_active
from cohorts c
left join public.analytics_events e
  on e.user_uid = c.user_uid
 and e.event_name = 'app_session_started'
 and e.timestamp >= c.cohort_day
group by c.cohort_day
order by c.cohort_day desc;

comment on view public.v_daily_active_users is
  'DAU by day. Powers the Product dashboard view. Service-role reads only.';
comment on view public.v_conversion_funnel is
  'Conversion funnel by day. Powers the Marketing dashboard view.';
comment on view public.v_cohort_retention is
  'D1/D7/D30 cohort retention. Powers the Product dashboard view.';

-- Dashboard views are owned by postgres (the migration runner). Grant read to
-- service_role explicitly so the FastAPI /revops/dashboard endpoint can query.
grant select on public.v_daily_active_users to service_role;
grant select on public.v_conversion_funnel to service_role;
grant select on public.v_cohort_retention to service_role;
