-- CoverWise RevOps tables (Phase R1.1)
-- Date: 2026-07-18
-- Convention: follow infra/supabase/001_coverwise_schema.sql and 003_rate_limit_windows.sql
--   - public schema
--   - owner_id text (NOT auth.users FK; Supabase user IDs are strings)
--   - created_at / updated_at timestamptz
--   - RLS enabled, all access revoked, only service_role granted
--   - Comments on every table
--
-- Apply via Supabase SQL editor or:
--   psql "$SUPABASE_DB_URL" -f supabase/migrations/2026_07_18_revops_tables.sql

-- ============================================================================
-- user_lifecycle: one row per user_uid, current lifecycle state
-- ============================================================================
create table if not exists public.user_lifecycle (
  user_uid text primary key,
  identity_type text not null check (identity_type in ('anonymous', 'account')),
  current_stage text not null check (current_stage in (
    'visitor', 'install', 'anonymous', 'account', 'activated',
    'power_user', 'paywall_viewer', 'paying', 'retained_paying',
    'churned', 'evangelist', 'stalled_power_user', 'at_risk', 'archived'
  )),
  stage_entered_at timestamptz not null default now(),
  engagement_score smallint not null default 0 check (engagement_score between 0 and 100),
  install_id uuid,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  archived_at timestamptz
);

create index if not exists idx_user_lifecycle_stage
  on public.user_lifecycle (current_stage);
create index if not exists idx_user_lifecycle_score
  on public.user_lifecycle (engagement_score desc);
create index if not exists idx_user_lifecycle_last_seen
  on public.user_lifecycle (last_seen_at desc);

alter table public.user_lifecycle enable row level security;

revoke all on table public.user_lifecycle from public, anon, authenticated;
grant select, insert, update, delete on table public.user_lifecycle to service_role;

comment on table public.user_lifecycle is
  'Per-user lifecycle stage and engagement score. One row per user_uid. Service-role only.';


-- ============================================================================
-- subscriptions: one row per provider subscription, current state
-- ============================================================================
create table if not exists public.subscriptions (
  subscription_id uuid primary key,
  owner_id text not null,
  billing_provider text not null check (billing_provider in ('dodo', 'razorpay')),
  provider_subscription_id text not null,
  created_via text not null default 'direct' check (created_via in ('direct', 'fallback')),
  plan_id text not null,
  plan_amount_paise bigint not null check (plan_amount_paise >= 0),
  currency text not null default 'INR',
  started_at timestamptz not null,
  current_period_start timestamptz not null,
  current_period_end timestamptz not null,
  cancelled_at timestamptz,
  cancellation_reason_bucket text check (cancellation_reason_bucket in (
    'too_expensive', 'no_value', 'switched_apps', 'privacy', 'other'
  )),
  expired_at timestamptz,
  grace_period_end timestamptz,
  status text not null check (status in (
    'active', 'past_due', 'cancelled', 'expired', 'in_grace'
  )),
  unique (billing_provider, provider_subscription_id)
);

create index if not exists idx_subscriptions_owner
  on public.subscriptions (owner_id);
create index if not exists idx_subscriptions_status
  on public.subscriptions (status);
create index if not exists idx_subscriptions_period_end
  on public.subscriptions (current_period_end)
  where status = 'active';
create index if not exists idx_subscriptions_provider
  on public.subscriptions (billing_provider);

alter table public.subscriptions enable row level security;

revoke all on table public.subscriptions from public, anon, authenticated;
grant select, insert, update, delete on table public.subscriptions to service_role;

comment on table public.subscriptions is
  'Canonical subscription state across Dodo + Razorpay. Provider-scoped UNIQUE prevents double-booking. Service-role only.';


-- ============================================================================
-- webhook_audit_log: every Dodo + Razorpay webhook hit (motto v3 §0.6 audit trail)
-- ============================================================================
create table if not exists public.webhook_audit_log (
  id bigint generated by default as identity primary key,
  received_at timestamptz not null default now(),
  provider text not null check (provider in ('dodo', 'razorpay')),
  provider_event_id text,
  event_type text,
  signature_valid boolean not null,
  processing_result text not null check (processing_result in (
    'processed', 'duplicate', 'rejected_signature', 'rejected_payload', 'failed_retry_queued'
  )),
  user_uid_hash text,
  latency_ms integer,
  error_class text
);

create index if not exists idx_webhook_audit_at
  on public.webhook_audit_log (received_at desc);
create index if not exists idx_webhook_audit_failed
  on public.webhook_audit_log (received_at desc)
  where processing_result in ('failed_retry_queued', 'rejected_signature');

alter table public.webhook_audit_log enable row level security;

revoke all on table public.webhook_audit_log from public, anon, authenticated;
grant select, insert, update, delete on table public.webhook_audit_log to service_role;

comment on table public.webhook_audit_log is
  'Every billing webhook hit. Audit trail per motto v3 §0.6. Service-role only.';


-- ============================================================================
-- processed_webhook_events: idempotency key (motto v3 §0.6)
-- ============================================================================
create table if not exists public.processed_webhook_events (
  provider text not null,
  provider_event_id text not null,
  processed_at timestamptz not null default now(),
  primary key (provider, provider_event_id)
);

alter table public.processed_webhook_events enable row level security;

revoke all on table public.processed_webhook_events from public, anon, authenticated;
grant select, insert, delete on table public.processed_webhook_events to service_role;

comment on table public.processed_webhook_events is
  'Idempotency key for billing webhooks. INSERT ON CONFLICT DO NOTHING. Service-role only.';


-- ============================================================================
-- failed_subscription_writes: rollback path (motto v3 §0.6)
-- ============================================================================
create table if not exists public.failed_subscription_writes (
  id bigint generated by default as identity primary key,
  failed_at timestamptz not null default now(),
  provider text not null,
  provider_event_id text,
  payload jsonb,
  error_class text,
  error_message text,
  retry_count integer not null default 0 check (retry_count >= 0),
  next_retry_at timestamptz,
  resolved_at timestamptz
);

create index if not exists idx_failed_writes_unresolved
  on public.failed_subscription_writes (next_retry_at)
  where resolved_at is null;

alter table public.failed_subscription_writes enable row level security;

revoke all on table public.failed_subscription_writes from public, anon, authenticated;
grant select, insert, update, delete on table public.failed_subscription_writes to service_role;

comment on table public.failed_subscription_writes is
  'Half-written subscription state captured for retry. Service-role only.';


-- ============================================================================
-- routing_decisions: audit log for every RevOps automation decision
-- ============================================================================
create table if not exists public.routing_decisions (
  id bigint generated by default as identity primary key,
  event_id bigint,
  event_name text not null,
  user_uid_hash text not null,
  decision_at timestamptz not null default now(),
  route_target text not null,
  reason_code text not null,
  metadata jsonb
);

create index if not exists idx_routing_decisions_at
  on public.routing_decisions (decision_at desc);
create index if not exists idx_routing_decisions_user
  on public.routing_decisions (user_uid_hash);

alter table public.routing_decisions enable row level security;

revoke all on table public.routing_decisions from public, anon, authenticated;
grant select, insert, update, delete on table public.routing_decisions to service_role;

comment on table public.routing_decisions is
  'Audit log for every RevOps automation routing decision. Stores user_uid_hash (one-way), never raw uid. Service-role only.';


-- ============================================================================
-- eval_set_candidates: auto-queued from negative feedback (motto v3 §0.6)
-- ============================================================================
create table if not exists public.eval_set_candidates (
  id bigint generated by default as identity primary key,
  document_id_hash text not null,
  question_length_bucket text not null,
  answer_confidence_bucket text not null,
  feedback_sentiment text not null,
  source_event_at timestamptz not null,
  reviewed_at timestamptz,
  reviewer_decision text check (reviewer_decision in (
    'accepted_into_eval', 'rejected', 'duplicate', 'fixed_inline'
  )),
  notes text
);

create index if not exists idx_eval_candidates_unreviewed
  on public.eval_set_candidates (source_event_at desc)
  where reviewed_at is null;

alter table public.eval_set_candidates enable row level security;

revoke all on table public.eval_set_candidates from public, anon, authenticated;
grant select, insert, update, delete on table public.eval_set_candidates to service_role;

comment on table public.eval_set_candidates is
  'Auto-queued negative-feedback events for operator review into evaluation_samples. Service-role only.';


-- ============================================================================
-- deal_decisions: deal desk audit log
-- ============================================================================
create table if not exists public.deal_decisions (
  id bigint generated by default as identity primary key,
  user_uid_hash text not null,
  decision_at timestamptz not null default now(),
  decision_type text not null check (decision_type in (
    'refund', 'discount', 'lifetime_deal', 'grace_period', 'beta_access', 'other'
  )),
  reason_code text not null,
  operator_notes text,
  related_subscription_id uuid
);

create index if not exists idx_deal_decisions_user
  on public.deal_decisions (user_uid_hash);
create index if not exists idx_deal_decisions_at
  on public.deal_decisions (decision_at desc);

alter table public.deal_decisions enable row level security;

revoke all on table public.deal_decisions from public, anon, authenticated;
grant select, insert, update, delete on table public.deal_decisions to service_role;

comment on table public.deal_decisions is
  'Operator-facing deal desk audit log. Tracks refunds, discounts, grace periods. Service-role only.';


-- ============================================================================
-- events_unrouted: fallback bucket for events with no matching automation
-- ============================================================================
create table if not exists public.events_unrouted (
  id bigint generated by default as identity primary key,
  event_name text not null,
  user_uid_hash text not null,
  received_at timestamptz not null,
  properties jsonb,
  reviewed_at timestamptz
);

create index if not exists idx_events_unrouted_unreviewed
  on public.events_unrouted (received_at desc)
  where reviewed_at is null;

alter table public.events_unrouted enable row level security;

revoke all on table public.events_unrouted from public, anon, authenticated;
grant select, insert, update, delete on table public.events_unrouted to service_role;

comment on table public.events_unrouted is
  'Events with no matching routing automation. Operator reviews weekly. Service-role only.';


-- ============================================================================
-- profiles.role: add operator role for RLS-based operator auth (Phase R1.9)
-- ============================================================================
-- This depends on a `profiles` table existing. The canonical plan calls for one
-- (per docs/planning/coverwise_supabase_canonical_plan_2026-07-16.md §"Product
-- and ownership data") but it is not in 001_coverwise_schema.sql yet. This
-- migration creates it if missing, and adds the role column.

create table if not exists public.profiles (
  user_uid text primary key,
  email text,
  display_name text,
  role text not null default 'user' check (role in ('user', 'operator')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Users can read their own profile.
-- Postgres does not support CREATE POLICY IF NOT EXISTS, so we guard with a DO block.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'Users read own profile'
  ) then
    create policy "Users read own profile"
      on public.profiles
      for select
      using (user_uid = auth.jwt() ->> 'sub');
  end if;
end
$$;

-- Service-role has full access (no policy needed for service_role bypasses RLS by default).
revoke all on table public.profiles from public, anon, authenticated;
grant select, insert, update on table public.profiles to authenticated;
grant select, insert, update, delete on table public.profiles to service_role;

comment on table public.profiles is
  'Per-user account metadata. role column gates operator-only access. Users can read their own row.';
