// Answer verification badge (ADR-2026-07-19-09 face 4).
//
// Renders the verification state of an answer as a compact chip next to the
// answer text. The badge is the UI face's contract: the user sees the
// verification state, not just the answer.
//
// Per ADR-2026-07-19-09 face 4:
//   1. The answer text is rendered alongside a verification badge
//      (fully_backed / partially_backed / abstained / unverified).
//   2. The UI never renders a number, fact, or recommendation as
//      "verified" without the badge.
import 'package:flutter/material.dart';
import '../widgets/shared/coverwise_components.dart';

/// The four verification statuses from the answer face (ADR-2026-07-19-09 face 3).
enum AnswerVerificationStatus {
  fullyBacked,
  partiallyBacked,
  abstained,
  unverified;

  /// Parse from the backend's lowercase snake_case string.
  static AnswerVerificationStatus fromString(String? value) {
    switch (value?.toLowerCase()) {
      case 'fully_backed':
        return AnswerVerificationStatus.fullyBacked;
      case 'partially_backed':
        return AnswerVerificationStatus.partiallyBacked;
      case 'abstained':
        return AnswerVerificationStatus.abstained;
      default:
        return AnswerVerificationStatus.unverified;
    }
  }

  String get displayLabel {
    switch (this) {
      case AnswerVerificationStatus.fullyBacked:
        return 'Evidence-backed';
      case AnswerVerificationStatus.partiallyBacked:
        return 'Partially backed';
      case AnswerVerificationStatus.abstained:
        return 'Could not verify';
      case AnswerVerificationStatus.unverified:
        return 'Not verified';
    }
  }

  IconData get icon {
    switch (this) {
      case AnswerVerificationStatus.fullyBacked:
        return Icons.verified_outlined;
      case AnswerVerificationStatus.partiallyBacked:
        return Icons.warning_amber_rounded;
      case AnswerVerificationStatus.abstained:
        return Icons.help_outline_rounded;
      case AnswerVerificationStatus.unverified:
        return Icons.info_outline_rounded;
    }
  }

  Color color(BuildContext context) {
    final theme = Theme.of(context);
    switch (this) {
      case AnswerVerificationStatus.fullyBacked:
        return theme.colorScheme.primary;
      case AnswerVerificationStatus.partiallyBacked:
        // Use a warm amber that works in both light and dark themes.
        return theme.brightness == Brightness.dark
            ? const Color(0xFFFFB74D)
            : const Color(0xFFE65100);
      case AnswerVerificationStatus.abstained:
        return theme.colorScheme.onSurfaceVariant;
      case AnswerVerificationStatus.unverified:
        return theme.colorScheme.tertiary;
    }
  }

  /// Tooltip text explaining what this status means to the user.
  String get tooltip {
    switch (this) {
      case AnswerVerificationStatus.fullyBacked:
        // CW-P0-009: Clarify that "evidence-backed" means every factual
        // claim has a citation that was verified against the source text.
        // This does NOT guarantee semantic entailment — the citation may
        // quote relevant text but the LLM's inference from it is not
        // re-checked. Users should still read the cited passages.
        return 'Every claim has a verified citation from your policy. Read the cited passages to confirm.';
      case AnswerVerificationStatus.partiallyBacked:
        return 'Some claims in this answer are verified, some are not. Cross-check with your policy.';
      case AnswerVerificationStatus.abstained:
        return 'This answer could not be verified against your policy documents. Verify independently.';
      case AnswerVerificationStatus.unverified:
        return 'This answer has not been verified yet. Verification is performed on answers generated by the system.';
    }
  }
}

/// A verification badge rendered next to Q&A answers.
///
/// Shows the [AnswerVerificationStatus] as a compact chip with icon, label,
/// and color. Includes a tooltip for the full explanation.
///
/// Compact by default to sit alongside confidence badges and action buttons.
class AnswerVerificationBadge extends StatelessWidget {
  final AnswerVerificationStatus status;

  const AnswerVerificationBadge({
    super.key,
    required this.status,
  });

  @override
  Widget build(BuildContext context) {
    return Tooltip(
      message: status.tooltip,
      child: CoverWiseStatusChip(
        icon: status.icon,
        label: status.displayLabel,
        color: status.color(context),
        compact: true,
      ),
    );
  }
}
